# First Nations observations

## Stock assessment

### 2019

- SOK product quality

### 2020

- Dive and surface survey work completed
- Sampling (e.g., castnets)
- Days spent surveying herring/spawn

### 2021

- FSC harvest (SOK): challenges and successes

### 2022

- Spawn intensity

### 2023

- Spawn timing

## Data summaries

### 2024

- Challenges to surveying spawn
- Work done
- Noteworthy spawns
- Spawn behaviour (depth, schools, holding)
- Fish behaviour
- Predators (whales, seals, sea lions, ducks)
- SOK/SOB success
- SOK/SOB challenges
- Spawn abundance and general locations
- Spawn trends and compared to historic

### 2025

- Temporal spread of spawn
- Spawn intensity, depth, size of spawns
- Fish size, age

# Questionnaire

- Name and email
- First Nation

- Maximum 300 words per response

1. Herring work done:
  a. Challenges and successes
  a. Days of effort
  a. Spawn surveys completed (dive and surface)
  a. Samples collected (e.g., castnets)

1. Herring and predators:
  a. Fish behaviour (e.g., depth, schools)
  a. Fish characteristics (e.g., size, age)
  a. Predators (e.g., whales, pinnipeds, birds)

1. Spawns:
  a. Spawn characteristics (e.g., duration, extent, intensity)
  a. Significant/noteworthy spawns (or lack of typical spawns)
  a. Abundance and trends (e.g., compared to last year/previous years)

1. FSC:
  a. Challenges and successes with SOK/SOB
  a. Product quality and quantity

1. Other comments
